INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'Full Stack Web Development Workshop','A comprehensive 3-day workshop covering React, Node.js, MongoDB, and deployment strategies. Industry experts from top tech companies will mentor participants.',c.id, c.department_id, 'workshop', 'offline', 'Seminar Hall A, CS Block',(CURRENT_DATE + INTERVAL '7 days')::date, '09:00', '17:00',499, 150, (CURRENT_DATE + INTERVAL '5 days'),'Basic HTML, CSS, JavaScript knowledge', ARRAY['web development', 'react', 'nodejs', 'fullstack'], true FROM clubs c WHERE c.name = 'Protocol Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'Placement Preparatory Session','GD, aptitude, and technical interview preparation by placement cell and alumni. Mock interviews with industry professionals.',c.id, c.department_id, 'seminar', 'offline', 'Main Auditorium',(CURRENT_DATE + INTERVAL '10 days')::date, '14:00', '18:00',0, 300, (CURRENT_DATE + INTERVAL '9 days'),'Final year or pre-final year students', ARRAY['placements', 'interviews', 'career'], true FROM clubs c WHERE c.name = 'Protocol Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'Hackathon 2026','24-hour hackathon with themed tracks: AI/ML, FinTech, Healthcare, and Sustainability. Prizes worth Rs 1,00,000. Top teams get mentorship from industry.',c.id, c.department_id, 'hackathon', 'offline', 'Innovation Hub, CS Block',(CURRENT_DATE + INTERVAL '21 days')::date, '09:00', '18:00',299, 200, (CURRENT_DATE + INTERVAL '18 days'),'Team of 3-4 members, programming experience', ARRAY['hackathon', 'innovation', 'coding'], true FROM clubs c WHERE c.name = 'CodeC Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'DSA Championship','Weekly competitive programming challenge. Problems from LeetCode, Codeforces, and company-specific patterns.',c.id, c.department_id, 'competition', 'online', 'Online Platform',(CURRENT_DATE + INTERVAL '5 days')::date, '20:00', '22:00',0, 500, (CURRENT_DATE + INTERVAL '4 days'),'Basic data structures knowledge', ARRAY['competitive programming', 'DSA', 'coding'], true FROM clubs c WHERE c.name = 'CodeC Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'Generative AI Bootcamp','5-day intensive bootcamp on LLMs, Stable Diffusion, and prompting. Hands-on projects with OpenAI APIs and open-source models.',c.id, c.department_id, 'workshop', 'hybrid', 'AI Lab, 3rd Floor',(CURRENT_DATE + INTERVAL '14 days')::date, '10:00', '16:00',999, 80, (CURRENT_DATE + INTERVAL '12 days'),'Python, basic ML concepts', ARRAY['generative AI', 'LLM', 'machine learning'], true FROM clubs c WHERE c.name = 'AI Research Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'ML Paper Reading Session','Weekly discussion on cutting-edge ML research papers. Guest lecturers from IISc and industry research labs.',c.id, c.department_id, 'seminar', 'offline', 'Room 301, CS Block',(CURRENT_DATE + INTERVAL '3 days')::date, '16:00', '18:00',0, 100, (CURRENT_DATE + INTERVAL '2 days'),'Interest in ML research', ARRAY['research', 'papers', 'ML'], true FROM clubs c WHERE c.name = 'AI Research Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'CTF Challenge 2026','Capture The Flag competition with web, crypto, forensics, and binary exploitation challenges. Partners with top security firms.',c.id, c.department_id, 'competition', 'offline', 'Security Lab, CS Block',(CURRENT_DATE + INTERVAL '28 days')::date, '10:00', '20:00',199, 150, (CURRENT_DATE + INTERVAL '25 days'),'Basic networking and Linux', ARRAY['CTF', 'security', 'hacking', 'pentesting'], true FROM clubs c WHERE c.name = 'Cyber Security Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'Ethical Hacking Workshop','2-day certification workshop on web application security, penetration testing, and vulnerability assessment. Certification included.',c.id, c.department_id, 'workshop', 'offline', 'Cyber Security Lab',(CURRENT_DATE + INTERVAL '35 days')::date, '09:00', '17:00',799, 60, (CURRENT_DATE + INTERVAL '32 days'),'Basic programming knowledge', ARRAY['ethical hacking', 'security', 'certification'], true FROM clubs c WHERE c.name = 'Cyber Security Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'Open Source Sprint','Contribute to open-source projects! Git workflows, PR processes, and real contributions to GitHub projects.',c.id, c.department_id, 'workshop', 'offline', 'Lab 2, IS Block',(CURRENT_DATE + INTERVAL '12 days')::date, '10:00', '17:00',0, 120, (CURRENT_DATE + INTERVAL '11 days'),'Git basics, any programming language', ARRAY['open source', 'github', 'collaboration'], true FROM clubs c WHERE c.name = 'TechNova Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'Data Analytics Summit','Industry-focused summit covering Tableau, Power BI, Python analytics, and SQL. Networking with data scientists from top companies.',c.id, c.department_id, 'seminar', 'offline', 'Conference Hall',(CURRENT_DATE + INTERVAL '18 days')::date, '09:00', '17:00',599, 100, (CURRENT_DATE + INTERVAL '15 days'),'Statistics basics, SQL knowledge', ARRAY['data analytics', 'visualization', 'business intelligence'], true FROM clubs c WHERE c.name = 'DataVerse Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'Deep Learning Intensive','2-weekend intensive on neural networks, CNNs, RNNs, and Transformers. Build projects on computer vision and NLP.',c.id, c.department_id, 'workshop', 'offline', 'AI Lab, AIML Block',(CURRENT_DATE + INTERVAL '25 days')::date, '09:00', '17:00',1299, 60, (CURRENT_DATE + INTERVAL '22 days'),'Python, NumPy, basic ML', ARRAY['deep learning', 'neural networks', 'AI'], true FROM clubs c WHERE c.name = 'Neural Nexus';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'Computer Vision Workshop','Hands-on workshop on object detection, image segmentation, and real-time video processing using OpenCV and TensorFlow.',c.id, c.department_id, 'workshop', 'offline', 'Vision Lab',(CURRENT_DATE + INTERVAL '40 days')::date, '10:00', '16:00',699, 80, (CURRENT_DATE + INTERVAL '38 days'),'Python, basic ML', ARRAY['computer vision', 'opencv', 'image processing'], true FROM clubs c WHERE c.name = 'Vision AI Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'IoT Innovation Challenge','Build smart IoT solutions for real-world problems. Arduino, ESP32, sensors, and cloud integration. Hackathon format.',c.id, c.department_id, 'hackathon', 'offline', 'Electronics Lab',(CURRENT_DATE + INTERVAL '30 days')::date, '09:00', '20:00',349, 100, (CURRENT_DATE + INTERVAL '27 days'),'Basic electronics', ARRAY['IoT', 'arduino', 'electronics', 'hardware'], true FROM clubs c WHERE c.name = 'CircuitVerse Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'RoboRace Competition','Annual robotics competition - build autonomous robots to navigate obstacle courses. Team event with prizes.',c.id, c.department_id, 'competition', 'offline', 'Robotics Arena',(CURRENT_DATE + INTERVAL '45 days')::date, '10:00', '18:00',599, 60, (CURRENT_DATE + INTERVAL '42 days'),'Team of 4-5 members, basic robotics', ARRAY['robotics', 'automation', 'hardware'], true FROM clubs c WHERE c.name = 'RoboTech Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'Renewable Energy Summit','Seminar on solar, wind, and sustainable energy technologies. Industry experts from NTPC, Tata Power, and startups.',c.id, c.department_id, 'seminar', 'offline', 'Seminar Hall B',(CURRENT_DATE + INTERVAL '15 days')::date, '10:00', '16:00',149, 150, (CURRENT_DATE + INTERVAL '13 days'),'Interest in energy systems', ARRAY['renewable energy', 'sustainability', 'green energy'], true FROM clubs c WHERE c.name = 'Spark Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'Drone Building Workshop','Build your own racing drone! 3-day workshop on drone design, flight controllers, and FPV systems.',c.id, c.department_id, 'workshop', 'offline', 'Aero Workshop',(CURRENT_DATE + INTERVAL '50 days')::date, '09:00', '17:00',2499, 40, (CURRENT_DATE + INTERVAL '47 days'),'Aerodynamics basics', ARRAY['drones', 'aerospace', 'UAV'], true FROM clubs c WHERE c.name = 'Aero Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'EV Design Challenge','Electric vehicle design competition - battery pack, motor, controller design. Winners showcased at Auto Expo.',c.id, c.department_id, 'competition', 'offline', 'Auto Workshop',(CURRENT_DATE + INTERVAL '55 days')::date, '10:00', '18:00',449, 80, (CURRENT_DATE + INTERVAL '52 days'),'Thermodynamics, vehicle dynamics', ARRAY['EV', 'automobile', 'electric vehicles'], true FROM clubs c WHERE c.name = 'AutoTech Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'Structural Design Competition','Bridge building and structural design competition using STAAD Pro. Industry judges from L&T, Tata Projects.',c.id, c.department_id, 'competition', 'offline', 'CAD Lab, Civil Block',(CURRENT_DATE + INTERVAL '60 days')::date, '09:00', '17:00',299, 70, (CURRENT_DATE + INTERVAL '57 days'),'Structural mechanics basics', ARRAY['structural design', 'civil engineering', 'CAD'], true FROM clubs c WHERE c.name = 'Nirman Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'BioTech Research Symposium','Showcase of biotechnology research projects. Guest lectures from Biocon, pharmaceutical companies, and researchers.',c.id, c.department_id, 'seminar', 'offline', 'Biotech Seminar Hall',(CURRENT_DATE + INTERVAL '65 days')::date, '10:00', '16:00',199, 80, (CURRENT_DATE + INTERVAL '63 days'),'Biosciences background', ARRAY['biotechnology', 'research', 'healthcare'], true FROM clubs c WHERE c.name = 'BioInnovators Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'Startup Pitch Challenge','Pitch your startup idea to VCs and angel investors. Mentorship worth Rs 50,000 for winners. Networking opportunity.',c.id, c.department_id, 'competition', 'offline', 'Incubation Center',(CURRENT_DATE + INTERVAL '20 days')::date, '14:00', '20:00',0, 60, (CURRENT_DATE + INTERVAL '18 days'),'Ready prototype or MVP', ARRAY['startup', 'entrepreneurship', 'pitching'], true FROM clubs c WHERE c.name = 'Entrepreneurship Cell';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'Pratibha 2026 - Annual Cultural Fest','BMSCE annual cultural festival with music, dance, drama, and art competitions. Inter-college participation.',c.id, c.department_id, 'cultural', 'offline', 'Open Air Theatre',(CURRENT_DATE + INTERVAL '90 days')::date, '10:00', '22:00',199, 1000, (CURRENT_DATE + INTERVAL '85 days'),'Performing arts interest', ARRAY['cultural', 'music', 'dance', 'drama'], true FROM clubs c WHERE c.name = 'Cultural Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'Acoustic Night','Unplugged music evening with college bands and solo performances. Open mic sessions!',c.id, c.department_id, 'cultural', 'offline', 'Amphitheatre',(CURRENT_DATE + INTERVAL '8 days')::date, '18:00', '22:00',49, 200, (CURRENT_DATE + INTERVAL '7 days'),'Music interest', ARRAY['music', 'live performance', 'open mic'], true FROM clubs c WHERE c.name = 'Cultural Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'Kreedotsav 2026 - Sports Fest','Annual sports fest with cricket, football, basketball, athletics, and indoor games. Inter-department competition.',c.id, c.department_id, 'sports', 'offline', 'Sports Complex',(CURRENT_DATE + INTERVAL '75 days')::date, '08:00', '20:00',149, 500, (CURRENT_DATE + INTERVAL '72 days'),'Sports interest', ARRAY['sports', 'athletics', 'competition'], true FROM clubs c WHERE c.name = 'Sports Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'Blood Donation Camp','NSS blood donation drive in association with Red Cross Society. Certificates for all donors.',c.id, c.department_id, 'workshop', 'offline', 'Medical Center',(CURRENT_DATE + INTERVAL '6 days')::date, '09:00', '17:00',0, 200, (CURRENT_DATE + INTERVAL '5 days'),'Medical fitness', ARRAY['blood donation', 'social service', 'NSS'], true FROM clubs c WHERE c.name = 'NSS Club';

INSERT INTO events (title, description, club_id, department_id, category, event_type, venue, event_date, start_time, end_time, registration_fee, max_participants, registration_deadline, prerequisites, tags, is_approved)
SELECT 'Photography Exhibition','Annual photography exhibition showcasing student works. Theme: "Bengaluru Through My Lens". Open to all.',c.id, c.department_id, 'cultural', 'offline', 'Art Gallery',(CURRENT_DATE + INTERVAL '70 days')::date, '10:00', '18:00',0, 300, (CURRENT_DATE + INTERVAL '68 days'),'Photography interest', ARRAY['photography', 'exhibition', 'art'], true FROM clubs c WHERE c.name = 'Photography Club';